# Generated by Django 2.1.3 on 2018-12-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word_status',
            name='correct_count',
        ),
        migrations.RemoveField(
            model_name='word_status',
            name='wrong_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='learnt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='difficulty',
            field=models.FloatField(default=0),
        ),
    ]
